# safelist
branches:
  only:
    - master
jobs:
  include:
    - stage: Test and lint ✅
      before_install:
        - npm i -g npm@8.11.0
        - npm i -g yarn@1.22.19
      language: node_js
      node_js: 16.16.0
      install: yarn
      script: yarn lint
     
