# safelist
branches:
  only:
    - master
jobs:
  include:
    - stage: Test and lint ✅
      before_install:
        - npm i -g npm@8.11.0
        - npm i -g yarn@1.22.19
      language: node_js
      node_js: 16.16.0
      install: yarn
      script: yarn lint
    - stage: Build Android 🤖
      before_install:
        - sudo apt-get install build-essential checkinstall && sudo apt-get install libssl-dev
        - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
        - source ~/.profile
        - nvm install 16.16.0
        - npm i -g yarn@1.22.19
      language: android
      dist: trusty
      android:
        components:
          - tools
          - platform-tools
          - build-tools-31.0.0
          - android-31
          - addon-google_apis-google-26
      sudo: true
      install:
        - yarn install
      jdk:
        - openjdk11
      script:
        - java --version
        - cd /usr/local/android-sdk/tools/bin
        - yes | ./sdkmanager --update
        - cd - && cd android && ./gradlew assembleRelease -x bundleReleaseJsAndAssets && cd ..
